### ISSUE TITLE
Bad interaction in style.css

### ISSUE THREAD

**Issue by pchampin** [nyergler/hieroglyph#18]
There are two rules in styles.css that interact badly, at least from my point of view; namely, those rules are:

``` css
ul:first-child {
  margin-top: 0;
}
ul ul {
  margin-top: .5em;
}
```

If you type the following ReST:

``` rst
* item 1
* item 2

  * sub-item 2.1
  * sub-item 2.2
```

then the sublist is the first child of the <li>, so the first rule (ul:first-child) overrides the second one (ul ul), resulting in "sub-item 2.1" being to close (vertically) to "item 2".
